ssh:
  shell:
    prompt:
      color: cyan
      text: 'basic::>'
    password: password
    authorized-public-keys-file: samples/complete/src/main/resources/.ssh/authorized.keys
    commands:
      jmx:
        create: false
      manage-sessions:
        create: false
      system:
        create: false

logging:
  level:
    com.github.fonimus: debug

info:
  build:
    groupId: ${project.artifactId}
    artifactId: ${project.groupId}
    version: ${project.version}
  dependencies:
    spring-boot: ${spring-boot.version}
    spring-shell: ${spring-shell.version}
